apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: add
  labels:
    app: add
spec:
  ingressClassName: ingress-appgateway
  rules:
  - host: add-task.ajay.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: add
            port: 
              number: 80
