apiVersion: apps/v1
kind: Deployment
metadata:
  name: get
spec:
  selector:
    matchLabels:
      app: get
  replicas: 3
  template:
    metadata:
      labels:
        app: get
    spec:
      containers:
      - name: get
        image: heroacr007.azurecr.io/todo-get:v1
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:ajaysqlserver007.database.windows.net,1433;Database=ajaysqldb007;Uid=achinta;Pwd=Raju@834068;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
